### ISSUE TITLE
Bug de vote __Yukihiro__

### ISSUE THREAD

**Issue by Yukihiro16** [pokepixelserv/pokepixelpublic#10]
En ce moment quand je vote, la récompense ne veut pas m'être admise 

-Screen-
![help](https://user-images.githubusercontent.com/29833345/27768619-fba53696-5f17-11e7-9fc9-3be43f67298d.PNG)

Merci de m'aider

**Comment by Flashback083** [comment]
Bizarre, mais là c'est le "Vérification en cours.." qui n'affiche pas la suite de la manip, du coup c'est plus coté site que serveur mais faudrait essayé avec un autre navigateur pour voir si ça vient pas d'une version obsolète :c

**Comment by Flashback083** [comment]
Aucune réponse je clôture ! Réouvre le ticket si ça se reproduit !
