### ISSUE TITLE
Quête légendaire

### ISSUE THREAD

**Issue by Azmagane** [pokepixelserv/pokepixelpublic#100]
La quêtes légendaire demandant de ramener des items / photos a quelques soucis.
Il faudrait la retester ( des joueurs sont bloqués sur les photos )

**Comment by SkyTizouk** [comment]
C'est fait !
Je t'aime Flash <3

**Comment by Flashback083** [comment]
J'ai rien fais sur ça xD
Mais c'est fix ?

**Comment by SkyTizouk** [comment]
C'est moi, enfaite il y a un problème de tag avec le changement de version et les photos ont changer du coup faut le changé via le menu NpcCustom !

**Comment by Flashback083** [comment]
Ok merci, je close !
