### ISSUE TITLE
"Duppli"

### ISSUE THREAD

**Issue by SkyTizouk** [pokepixelserv/pokepixelpublic#103]
Tête d'ender dragon se pose mais qui reste dans la main quand on la pose.

**Comment by Flashback083** [comment]
Voldemort a essayé mais le bug il ne l'a pas dans sa main, peux-tu me confirmer si le bug est toujours présent ? 
Merci !

**Comment by Flashback083** [comment]
A verif : c'est quand on le casse

**Comment by SkyTizouk** [comment]
Mais j'ai vérifier moi même x)

**Comment by Estreillia** [comment]
Il avaiy deja eu un github a se sujet ou zkulls en a parlé en staff_important et ont n'avait dit que c'est pas si grave si c'était juste un tête d'ender dragon

**Comment by Zkulls** [comment]
oui j'en avais parlé c'quand tu le casse

**Comment by SkyTizouk** [comment]
Edit du coup : Toutes les têtes

**Comment by Flashback083** [comment]
apparemment fix
