### ISSUE TITLE
petit soucis dans les claims

### ISSUE THREAD

**Issue by Zkulls** [pokepixelserv/pokepixelpublic#105]
Un problème qui revient souvent c'est le faite que les joueurs ne puissent pas cassé les bûches des arbres dans leurs claims

**Comment by Zkulls** [comment]
en passant vue que c'est en rapport avec les claims je peux posé bloc et détruire dans les claims des joueurs sans devoir être trust alors que normalement en tant que modo on pouvait pas  (on peut pas ouvrir coffre par contre j'ai test)

**Comment by Flashback083** [comment]
Plop, peux-tu me confirmer si le bug est toujours présent ? Merci !

**Comment by Zkulls** [comment]
pour les bûches d'arbre apparement j'ai demandé à ceux connecté ils ont pu eu le soucis juste Deker qui a dit que après quelques minutes il a pu détruire. En ce qui concerne le faites que je suisse posé des blocs maintenant c'est bien bloqué mais quand je spam pour posé ou cassé ça fonctionne à partir d'un moment.

**Comment by Zkulls** [comment]
![2019-05-23_15 59 24](https://user-images.githubusercontent.com/44169217/58260666-29f4cc80-7d77-11e9-9939-722446bf2bca.png)

**Comment by Flashback083** [comment]
Problème des buches normalement fix

**Comment by Flashback083** [comment]
Edit: apparement non

**Comment by Zkulls** [comment]
Effectivement non je viens à l'instant d'aidé un joueur a détruire un arbre dans un claim ^^
