### ISSUE TITLE
Bug de shulker

### ISSUE THREAD

**Issue by Flashback083** [pokepixelserv/pokepixelpublic#107]
Apparemment on peut poser sa shulker en dehors d'un claim, voir pour fix

**Comment by Estreillia** [comment]
Un modo a test ? ou c'était un joueur ?

**Comment by Flashback083** [comment]
Un joueur, mais je viens de tester avec mon double compte et voilà ce qui se passe : 
Tu pose en dehors du claim, ça te marque que ta pas le droit mais tu perds l'item en main

**Comment by Estreillia** [comment]
C'est seulement un bug visuel, normalement ouvre ton inventaire puis clique (pour prendre item) dans le slot ou il avait la shulkeur

**Comment by Flashback083** [comment]
j'ai pas l'impression mais je vais ressayer

**Comment by Flashback083** [comment]
Nop j'ai vraiment l'impression que je le perds

**Comment by Estreillia** [comment]
ha merde, bon bah bonne chance pour trouver une soluce

**Comment by Flashback083** [comment]
Ah bah ya pas que les shulkers ça me le fait pour tout les blocks
