### ISSUE TITLE
ClearLag

### ISSUE THREAD

**Issue by Flashback083** [pokepixelserv/pokepixelpublic#110]
Essayer de remettre le plugin ClearLag

**Comment by Estreillia** [comment]
Le clear lag marche niquel aucun lag apparent jusqu’a mtn, mais peut etre mettre certain objet qui ne sokt pas delete lors du clear lag comme les shulkeurs

**Comment by Flashback083** [comment]
Le plugin n'est pas encore remis, il y sera au prochain redem normalement mais ok je vais voir pour les shulkers !

**Comment by Estreillia** [comment]
Ha bon portant sa fait 1 semaine que ya un clearlag

**Comment by Flashback083** [comment]
Oui mais comment dire : 
En gros avant, il y en avait un via un plugin, il marchait bien, mais avec certaines mises à jour, le texte avait planté
Donc j'avais codé mon plugi pour delete les items
Mais là je vais reessayer de remettre une version du plugin avec le texte qui fonctionne, et j'ai ajouté les shulker en whitelist donc ça ne devrait plus les supprimer, a  tester après le redem de 00h

**Comment by Estreillia** [comment]
Ok ok 👌
