### ISSUE TITLE
Azma TEST

### ISSUE THREAD

**Issue by Azmagane** [pokepixelserv/pokepixelpublic#112]
Pourrais-tu ajouter ceci dans le dossier datapacks du serveur azma :
https://mega.nz/#F!w2pD3Q5C!qllsOswOBDJAYGDlKlu5hw
Merci bien ! ☻

**Comment by Flashback083** [comment]
Je n'ai pas de dossier datapack

**Comment by Flashback083** [comment]
https://gyazo.com/1f8df4674534b25cb75e12387529cb90

**Comment by Azmagane** [comment]
Dans le dossiers "world" ça devrait y être

**Comment by Flashback083** [comment]
essaye de redem mais je sais pas si ça va marcher

**Comment by Azmagane** [comment]
Je viens d'aller en jeu aucune de mes fonctions n’apparaissent, pourtant il suffit juste de copier coller le dossier que j'ai envoyé dans le dossier datapacks ( non zip ), j'avais testé en solo pour être sûr.

**Comment by Flashback083** [comment]
envoie un screen de ton mode solo

**Comment by Azmagane** [comment]
http://www.noelshack.com/2019-21-5-1558651733-1.png ça c'est pour le solo
J'ai aussi testé sur mon serveur et j'ai fait comme ci dessus :
world > datapacks et la j'ai paste mon dossier semitd
http://www.noelshack.com/2019-21-5-1558651907-2.png

**Comment by Flashback083** [comment]
et Là ?

**Comment by Azmagane** [comment]
Je confirme qu'elles sont toutes présentes, merci bien :)
