### ISSUE TITLE
Recompence lors de découvertes de bug ?

### ISSUE THREAD

**Issue by Estreillia** [pokepixelserv/pokepixelpublic#116]
Ils faudrait donner des recompences au joueurs si il trouve des bug, et il faudrait juger pour donner la recompence selon le bug trouvé, sa inciterais au joueur de pas abuser du bug et de le rapporter pour recevoir une recompences

ps: bonne idée ZeFious ^^

**Comment by Flashback083** [comment]
Ajouter dans le réglement les joueurs seront prévenu
