### ISSUE TITLE
Réu du 25/05/2019

### ISSUE THREAD

**Issue by Flashback083** [pokepixelserv/pokepixelpublic#118]
- Calendrier 
- EventV6
~~- Casino / JS~~
~~- Faire début java pour ensuite idée UG~~ Plus tard

**Comment by Elecrton78** [comment]
-  Ajouter les Item types : Pepite, Gros Champi, Perle, Encens, ... en vente au warp shop.

**Comment by Estreillia** [comment]
Ajouter des objets a vendre au warp shop

**Comment by Flashback083** [comment]
@Elecrton78 Si possible me donner les items en anglais, et un prix mini :p

**Comment by SkyTizouk** [comment]
Les encens à 1500/u je pense.
• ~~Full Incense~~
• ~~Lax Incense~~
• ~~Luck Incense~~
• ~~Pure Incense~~
• ~~Odd Incense~~
• ~~Rock Incense~~
• ~~Rose Incense~~
• ~~Sea Incense~~
• ~~Wave Incense~~
Pour le reste à vous de juger :
• Nugget
• Big Pearl
• Pearl String
• Big Mushroom
• Balm Mushroom
• Tiny Mushroom
Il en manque peut-être mais au moins ceux-ci sont déjà listés.
On pourrais ajouter les plaques par exemple, ou encore les lettres etc
Je pense aussi qu'il faudrait légèrement monté le prix des minerais qui sont vraiment devenus pas rentable :/

**Comment by Elecrton78** [comment]
Pour les encens chuis ok mais ouai Big pearl ect on pourrais prendre le prix des jeux je pense 
![image](https://user-images.githubusercontent.com/50781596/58506399-81d46e80-818f-11e9-99c8-a0862a251256.png)

La pearl string a 25k dans le jeu aussi

**Comment by SkyTizouk** [comment]
Ça fait chère je trouve non ?

**Comment by Estreillia** [comment]
Le plus cher 4800 tu vend 4 emeraude ta sa xD apres a toi de voir, mais je trouve pas sa cher

**Comment by Elecrton78** [comment]
La pearl string le seule moyen de l'avoir c'est Mega canne 3 point d'exclamation en océan (tres rare de ouf je tombe que sur des truc pour kyogre)

**Comment by Flashback083** [comment]
Faire la liste des items manquant au shop avec leur prix
