### ISSUE TITLE
Grades Aide

### ISSUE THREAD

**Issue by Maily971** [pokepixelserv/pokepixelpublic#119]
(pour flash) 
pense a creer les grades aide stp ^^' 
d'après Azmagane il faudrait le gm , fly , perms build 
et d'après moi il faudrait en plus de cela les perms npcs et peut être mais la je suis pas sure les commands blocks mais a voir pour ce dernier pour questions de logique

**Comment by SkyTizouk** [comment]
Mais du coup le grade servirais à quoi ?
Puisque c'est globalement ce que celui déjà en place apporte :x

**Comment by Estreillia** [comment]
Cest presque le meme mais sans world edit

**Comment by Azmagane** [comment]
Le grade aide actuel donne le grade anim, or si on veut qu'un joueur devienne un "aide anim" ça serait problématique qu'il ai toutes les perms et le grade.
Il faudrait 2 grade aides :
"Petite aide" qui donne le gm, sethome et tp
"Grande aide" qui donne en plus le WE, kick, mute, ban

**Comment by SkyTizouk** [comment]
Donc en soit, le "Grand aide"c'est le même que celui déjà existant ?
Et le "Petit aide" est bon. A mettre en place du coup oui ^^
