### ISSUE TITLE
Bras mouvant ?

### ISSUE THREAD

**Issue by Estreillia** [pokepixelserv/pokepixelpublic#121]
Un joueur ''xagatsu'' a un bug qu'il fait que sa vision tourne dans tous les sens et ses bras bouge aussi dans tous les sens, mais il est le seul a le voir !

**Comment by Flashback083** [comment]
Faudrait essayer de le /kill

**Comment by Estreillia** [comment]
J'ai pas la perm, mais le /suicide regle rien

**Comment by Flashback083** [comment]
et redem launcher ?

**Comment by Estreillia** [comment]
aussi

**Comment by Estreillia** [comment]
redem pc aussi

**Comment by Estreillia** [comment]
delete et retelecharger tous les dossier aussi

**Comment by Flashback083** [comment]
Argh, compliqué, faudrait essayé avec un autre launcher, il a un compte premium ?

**Comment by Estreillia** [comment]
Il ta contacter ? Il ma dit qu’il le ferrait

**Comment by Flashback083** [comment]
nop ou alors j'ai pas fais gaffe

**Comment by Estreillia** [comment]
Sont pseudo sur le discord c’est ..... ou un truc du genre

**Comment by Flashback083** [comment]
ah lui le problème cetait pour la boutique apparement

**Comment by Estreillia** [comment]
Ha oui tromper de mp

**Comment by Estreillia** [comment]
Mais je pense que tu peut le fermer, il va refaire comme la derniere fois revenir dans un mois

**Comment by Flashback083** [comment]
ok xD
