### ISSUE TITLE
récompense du drf take

### ISSUE THREAD

**Issue by voldemort5** [pokepixelserv/pokepixelpublic#122]
la récompense du jour 26 est un un rubis (celui des cré) mais il sert strictement à rien car ça sert à crafter une chaine rouge que l'on peut pas utiliser car les altar sont désactiver il faudrait le remplacer par autre chose (je ne sais pas quoi)

**Comment by Zkulls** [comment]
la chaîne sert pas pour la quête du cimetière?

**Comment by voldemort5** [comment]
Ah possible je ne sais pas je n'ai pas encore fais la quête

**Comment by Flashback083** [comment]
26 : coffre "grassium Z" etc
10 : 50 pb
