### ISSUE TITLE
Bug viseul dans les ultra brèches

### ISSUE THREAD

**Issue by MrDracoboy62** [pokepixelserv/pokepixelpublic#124]
Bonsoir, j'ignore si certains ont le même problème ou non, mais lors de mes escapades chimériques (depuis la maj en 7.0.6 du mod) j'ai une certaine difficulté à voir où je vais dans la dimension. Pour illustrer mon propos, voilà comment je vois une "queue de comète" (comme j'aime les appeler) dans la dimension:
![2019-05-28_01h14_59](https://user-images.githubusercontent.com/51105090/58448172-4beba780-8107-11e9-8697-f2d49ee22d18.png)

La couleur semble changer selon le biome ou l'heure de la journée, mais cette purédpois n'était pas présente avant la maj du serveur.
Et pour ceux se posant la question des lunettes filtres (permettant de voir mieux quand équipées), ça me rajoute 1 mètre de visibilité à tout casser :/

**Comment by DaeM0nS** [comment]
Yop! Effectivement, c’est la nouvelle mise à jour qui fait ça. Debase c’était sensé l’être depuis le début mais Jay (un dev pixelmon) l’avait réduit pour des tests.. essaie de voir pour diminuer le Fog directement sur ton client via les réglages ou optifine. Après, je ne saurais pas vraiment quoi te dire de plus ://

**Comment by MrDracoboy62** [comment]
alors en bidouillant un peu les configs du joueurs, tu peux faire en sorte d'y voir un peu plus:
pour ça en passant par le launcheur (pour ceux qui verraient le message et voudraient savoir comment on fait) tu actives l'engrenage en haut à droite pour accéder à la console, tu tapes 6 pour accéder au fichier, tu appuies sur .PokéPixel dans la barre en haut pour sélectionner le fichier bloc-notes optionsof et tu modifies les 2 premières lignes
J'ai mis ces 2 données là histoire d'être tranquille : 
![2019-05-28_16h27_21](https://user-images.githubusercontent.com/51105090/58486281-d9f67b00-8165-11e9-93cb-ceb991cbf970.png)

Une fois revenu dans les ultra brèches, le fog est toujours présent mais comme dit dans les configs, ça se passe bien plus loin (genre là je vois à 10 chunks sans soucis d'opacité) :)

**Comment by MrDracoboy62** [comment]
la solution a pas marché longtemps btw xD

**Comment by Flashback083** [comment]
Ah xD
Mais là on pourra rien faire de notre coté jpense :p
