### ISSUE TITLE
Mettaton le chômeur 

### ISSUE THREAD

**Issue by Kiri08** [pokepixelserv/pokepixelpublic#125]
![unknown](https://user-images.githubusercontent.com/51129053/58492777-e7196700-8171-11e9-88d0-a9ff744244a9.png)
 Voilà tout est dit dans le screen, j'en suis à 11 jours de daily reward et Mettaton veut pas que je fasse son quizz (ça fais 2 jours qu'il me met le message).

**Comment by Estreillia** [comment]
Le bug est present pour moi, aussi, je pense c'est le cas pour tous les joueurs

**Comment by Flashback083** [comment]
Bizarre, je viens de le faire avec mon autre compte, j'ai récupéré le jour 8, ça a marché sans soucis

**Comment by Flashback083** [comment]
c'est quoi ton pseudo ?

**Comment by Kiri08** [comment]
Kiri

**Comment by Flashback083** [comment]
Pas de bug avec mon compte, je l'ai donné a Kiri manuellement, à voir si ça se reproduit
