### ISSUE TITLE
Bug avec les baies nanao

### ISSUE THREAD

**Issue by Tsuyokami** [pokepixelserv/pokepixelpublic#13]
en Semi-rp il y a des plantes de baie nanao qui ne disparaisse pas apres avoir clicker dessus, elle donne des baies a l'infinie et marque un message " you don't have a wilderness administrator's permission to build here"
J'ai pris quelques screens pour prouver que les plantes sont belle et bien buguer.
![2017-08-25_10 47 57](https://user-images.githubusercontent.com/31340362/29706670-efadedac-8982-11e7-9afb-fefcfebe3427.png)

![2017-08-25_10 40 35](https://user-images.githubusercontent.com/31340362/29706680-f9ce9174-8982-11e7-8b4a-5955085caee5.png)

![2017-08-25_10 26 41](https://user-images.githubusercontent.com/31340362/29706689-0237c682-8983-11e7-9e06-29982f68ced3.png)

**Comment by Flashback083** [comment]
Normalement fix, merci de me le confirmer !
