### ISSUE TITLE
Clear lag ne clear pas tous ?

### ISSUE THREAD

**Issue by Estreillia** [pokepixelserv/pokepixelpublic#133]
Lors du clear lag tous les items genre block ont été clear, mais tous ce qui est graine, charbon fragment pierre foude ont pas été clear

**Comment by Flashback083** [comment]
Hello, dis moi, tu étais a coté de l'item quand le clear a été fait ? Ou tu es retourné dans une zone qui avait l'item drop ?

**Comment by Estreillia** [comment]
Oui jetait a coter

**Comment by Flashback083** [comment]
si tu reste devant jusqu'au prochain clear, ça clear ou jamais ils partent ?

**Comment by Flashback083** [comment]
Ok, ça le fait avec d'autres item, je vais verif ça merci

**Comment by Flashback083** [comment]
A verif au prochain redem serveur
