### ISSUE TITLE
/s ou /sc bloqué en jeux ?

### ISSUE THREAD

**Issue by Estreillia** [pokepixelserv/pokepixelpublic#134]
Serais t-il possible de faire en sorte que l'ont puissent voir ou ne pas voir le channel staff en jeux ?

**Comment by Flashback083** [comment]
Impossible je pense

**Comment by Flashback083** [comment]
Ou alors, il faudrait tout simplement enlever la perm pendant le temps que tu veux désac, ce qui est "possible"
