### ISSUE TITLE
système Apprenti/Maitre

### ISSUE THREAD

**Issue by M-Lockpin** [pokepixelserv/pokepixelpublic#135]
Ce serait faire un système d'apprentie et de maître/enseignant en strat
Les gens dit "bons" en strat aurait un apprenti et lui apprendrais la strat dans le fons etc...
Sur discord faire un beau channel pour ceux qui veulent être apprenti
MAIS
si on fait juste comme ça personne viendra
DONC
faudrait de 1) faire de la pub sur le serv à l'aide au pire d'un message régulier
2) limite octroyé une récompense si l'apprenti fait des perf à un tournoi

Zefious a demandé qui payerai la récompense : le serveur ce serais mieux, ça serait comme du parrainage en fait, à peu près

**Comment by Flashback083** [comment]
Plop, l'idée d'enseigner la strat n'est pas mauvaise, pourquoi pas effectivement, mais la récompenser si perf, je trouve ça pas terrible, je m'explique : 
Il faudrait juger sur plusieurs tournois, et pas genre 2-3, genre plus car il peut juste avoir eu de la chance sur certains matchmaking
Aussi vu qu'il faut évaluer sur plusieurs match, donner une récompense me parait compliqué tout ça est plutôt au cas par cas
Donc pour l'histoire de gens qui enseigne la strat, il faudrait aussi savoir qui serait motivé pour le faire ? Pas une seul personne suffirait je pense, et faut voir qui aurait du temps pour ça

**Comment by M-Lockpin** [comment]
Alors oui et oui.
Faire sur plusieurs tournoi ou alors dépendant de qui il affronte si le petit poussin bat Elec ou Nashira ou d'autres bons que je ne peux pas citer il pourrait gagner un petit bonus.
PAR CONSEQUENT oui ce serait surement du cas par cas.
MAIS il faut absolument une récompense car sinon ça attirera personne et faire des tournois à 10 alors qu'il y a 60 joueurs de co c'est pas ouf du tout :/
Donc le cas par cas semble assez inévitable mais c'est ptet pas si grave car il va pas y avoir tant de joueurs parrains il faudrait demander à certains s'ils veulent bien.
Mais en faisant ça pourrais potentiellement level-up le niveau strat du serv même si les champs font un peu déjà mais pas assez malheureusement.

**Comment by M-Lockpin** [comment]
au pire si un jour tu veux vocal pour en discuter y a pas de soucis

**Comment by SkyTizouk** [comment]
C 'est malheureusement quelque chose qui demande du temps, il faut pour mettre en place cela, quelqu'un de bon stratégiquement, qui ai du temps, qui soit au contacte des joueurs fréquemment afin d'introduire/gérer ce système Maître/Enseignant, que les hauts gradés aient confiance en lui, et en ceux qu'il gèrera (Car les récompenses viennent pas du ciel, mais du give) etc

**Comment by M-Lockpin** [comment]
Pour ce qui est du temps les vacances arrivent + contact des joueurs bah j'ai envie de dire que c'est pas un problème pour beaucoup :/ C'est plutôt vous qui êtes moins en contact même si vous pouvez peut-être pas ce que je comprend et respecte. Ce qui est de la confiance, bah à vous de jugez en qui vous avez confiance mais des gars comme Nashira ou Deker je pense que ça devrais pas poser trop problème.
Après pas obligé de mettre tous ce que tu as dit sur le dos d'une seule personne, ça peut être un groupe de personne et qui à eux tous respecte tous les critères.
