### ISSUE TITLE
[Pixelmon Semi-RP] Pokémon qui disparaît avec la commande /wt

### ISSUE THREAD

**Issue by Athems** [pokepixelserv/pokepixelpublic#14]
Bon voilà le résumé:

Tout à l'heure, j'avais 6 poké sur moi dont un nul que je garde toujours pour le WonderTrade.
Cette fois il était dans le slot 6 donc j'utilise le /wt 6 puis le confirme.
Sauf que le pokémon reçu s'est placé dans le slot numéro 3
Mais il se trouve que Mon Xerneas se trouvait justement dans se même slot et en a été **VIOLEMMENT** dégagé. Sur le coup un petit coup de stress suite à cette perte. Je demande l'aide aux modos, me connecte sur le discord,etc... mais aucun n'est disponible.
Du coup je commence par prévenir les autres joueurs de ne pas utiliser la commande pour qu'il ne perde rien, je vais vérifier la boite de mon PC (je ne vérifie que la 1ère car c'est la seule que j'utilise) , il n'y est pas.
Donc je patiente 30min / 1h puis dans le doute, je retourne au PC afin de vérifier les autres boites même si je ne les utilisent jamais... et là petite surprise, le Xerneas était dans la boite 3 (bon c'est peut-être un hasard mais visiblement ce bug l'a envoyé dans le numéro de boite qui est le même que celui du slot dans lequel il se trouvait) J'en ai donc rapidement parlé à Iruuyami juste après qui m'a conseillé de faire un ticket étant donné que je lui ai dit qu'il faudrait l'ajouter à la liste des bugs même si mon problème était réglé

Donc voilà ce n'est pas un bug très grave mais je penses qu'il faudrait malgré tout l'ajouter à la liste, ça éviterait aux joueurs de galérer pendant trop longtemps en se disant qu'ils ont perdu leur pokemon, et ils n'auraient ainsi pas à déranger les modérateurs avec ce problème.

_Merci de votre compréhension pour ce **PETIT** message !_

**Comment by Flashback083** [comment]
Plop ! Ce qu'on va faire je pense c'est désactiver le mod wondertrade il n'est peut être pas bien compatible avec les nouvelles versions de pixelmon, ravi de savoir que tu as quand même pu récupérer ton pokémon.
Je l'enlèverais ce soir je pense, merci de ton message !
