### ISSUE TITLE
Kit food

### ISSUE THREAD

**Issue by Estreillia** [pokepixelserv/pokepixelpublic#140]
Tu veut que les joueurs fasse quoi avec 5 pains xD ? En plus le coldown est que 1h, faudrait soit mettre genre 15 pain dans le kit ou mettre un cooldown de 15 minute .

**Comment by Flashback083** [comment]
1 stack ça va ?

**Comment by SkyTizouk** [comment]
Personnellement, je trouve que le kit enlève le coté Rp, y'a plus d’intérêt d'avoir des champs si le kit les donnent directement.

**Comment by Estreillia** [comment]
rp n'importe disont que quand tu arrive sur le serveur tu a pas le temp de claim puis faire un champ, alors bon, soit add plus de pain ou créer un kit bienvenue o yaurais genre 1 stack de steak + d'autre truc pour bien commencé

**Comment by Flashback083** [comment]
L'idée serait de faire un /kit start possible une seul fois.. Ou alors juste voir pour donner des items quand le joueur se co la première fois
