### ISSUE TITLE
Monde Ressources

### ISSUE THREAD

**Issue by Estreillia** [pokepixelserv/pokepixelpublic#141]
Bonjour/Bonsoir, les systeme de redstone possible pour faire des clock ne sont plus possible, car les items pour ont été ban, alors il serait bien de remmetre les structures en monde ressources, sa ajouterais un peu plus de decor, genre si tu veut recup des block qui spawn que par structure pour faire ta deco, bah tu peut pas les obtenir, il est aussi possible de retiré les structures pixelmon et garder seulement les structures vanilla

Aussi autre suggestion, rajouter les mobs en monde nether ou ressources pourrait ajouter un peu plus de difficulté lorsque tu mine, car je trouve le systeme PVE très peu présent outre que Shannox et Yasuo, vous me direz que c'est un serveur pixelmon, pas PVE, mais c'est toujours nice du pouvoir tapper du monstre de temp en temp(tkt azma j'ai pas oublier ton TD)

**Comment by Flashback083** [comment]
Pour le 1)
Je sais pas si c'est possible de garder que ceux vanilla, c'était comment le reset d'avant ?
Pour le 2)
Bof, j'avais déjà voulu faire ça et les joueurs étaient pas super fan
Mais c'est un truc que je prévois pour le prochain projet #v6

**Comment by SkyTizouk** [comment]
Certaines structures vanilla présente les objets pour faire de la duppli.
Quel est le rapport avec les clocks puisque de toutes manière les clocks sont interdites, d'autant plus que le système ne nécessite pas de clocks pour duppli.
