### ISSUE TITLE
Héphaïst

### ISSUE THREAD

**Issue by M-Lockpin** [pokepixelserv/pokepixelpublic#146]
Quand on a 0 Pokédollar il fait quand même le changement de ball

**Comment by Flashback083** [comment]
Où est le pnj ? Coordonnées (x y z)

**Comment by Zkulls** [comment]
X:10498 Y:71 Z:9241

**Comment by Flashback083** [comment]
Impossible a fix sans faire un plugin ou une quête qui demande des coins purse
