### ISSUE TITLE
Capacité extern

### ISSUE THREAD

**Issue by Estreillia** [pokepixelserv/pokepixelpublic#147]
les capacité extern ont été retiré, car diancie pouvais transformer le charbon en diams, alors est ce que c'est possible de les mrettre mes desact que celle de diancie, pck y'ern a qui sont utile telle que doux parfum(ou un nom de genre)qui permet d'obtenir floette d'AZ

**Comment by Flashback083** [comment]
Faudrait voir si ya pas une capacité trop chiante ? Genre le TP d'abra :/
