### ISSUE TITLE
/mpm name

### ISSUE THREAD

**Issue by DeKerX150** [pokepixelserv/pokepixelpublic#162]
Retirer la commande /mpm name au dresseur/topdresseur/pokélite/master.

**Comment by Zkulls** [comment]
pour le pourquoi je dirais que si tout le monde le fait on s'y retrouvera plus avec les pseudo, limite retirer pour le staff aussi. Si on le laisse au staff au moins dire qu'ils doivent avoir le pseudo lisible que les joueurs puissent les reconnaitre. ( Le truc c'est que si on laisse au staff les joueurs vont surement râlé sur ce fait ^^)

**Comment by DeKerX150** [comment]
Y a surtout aucune limite a ce que tu peux mettre, tu peux tre bien mettre 30000 "a" ou ecrire "nique ta mere" donc bon :/

**Comment by Zkulls** [comment]
Oui aussi
