### ISSUE TITLE
Cosmog/Cosmovum

### ISSUE THREAD

**Issue by DeKerX150** [pokepixelserv/pokepixelpublic#166]
Ajouter Cosmog et Cosmovum dans la boutique du site :)

**Comment by Flashback083** [comment]
le deuxieme c'est juste l'évolution, pas sur que ce soit super utile

**Comment by DeKerX150** [comment]
Bah c'est comme tu veux en soit les 2 sont des leg en soit donc bon ^^

**Comment by Flashback083** [comment]
ouai mais de base je viens de me souvenir que je les avais pas mis car il y a directement solga et lautre

**Comment by DeKerX150** [comment]
ouai fin du coup y aucun autre moyen de l'avoir mise à part avoir la chance de le faire spawn ou de le drop en coffre random :/

**Comment by Flashback083** [comment]
jvais mettre le petit a la limite

**Comment by DeKerX150** [comment]
ok 👌
