### ISSUE TITLE
Warp evs

### ISSUE THREAD

**Issue by Yuuki59** [pokepixelserv/pokepixelpublic#180]
Pour les modo
-vanish (avoir la perm) surtout quand on à le bug des poké invisible :x            
-toute les autre commande pour évité de quitté rien que pour l'écrire....

**Comment by Flashback083** [comment]
Pas compris le 2eme

**Comment by Yuuki59** [comment]
Exemple : un joueur me demande de faire une commande, je dois quitter le warp evs pour le faire

**Comment by Flashback083** [comment]
Donc autorisé le /spawn au modo et + ?

**Comment by Yuuki59** [comment]
Oui car Re payer non merci x)

**Comment by Flashback083** [comment]
Faut verifier si c'est bon
