### ISSUE TITLE
Kits

### ISSUE THREAD

**Issue by M-Lockpin** [pokepixelserv/pokepixelpublic#206]
Depuis le grade stagiaire ou après la résolution du bug des homes ( je sais pas trop depuis quand je m'en suis aperçu qu'aujourd'hui ), j'ai accès aux kit TopDresseur ET Pokelite alors que je suis Pokelite.

**Comment by Flashback083** [comment]
Check si c'est good now

**Comment by M-Lockpin** [comment]
mon mauvais mais je viesn de vérifier et ça marche toujours pas enfin toujours accès au kit pokédresseur
