### ISSUE TITLE
Fossile disparaisse 

### ISSUE THREAD

**Issue by Flashback083** [pokepixelserv/pokepixelpublic#22]
Plus d'info

**Comment by Nukeplayed** [comment]
Je ne serais pas régler se problème, mais je sais que j'avais plusieurs Pokémon fossiles comment x2 Ptera, Carapagos, x2 Amagara et Lilia. ils ont tous disparue de mon pc genre 1h après les avoir eu

**Comment by Flashback083** [comment]
J'aimerais plutôt que tu me dise comment ils ont disparu et comment je dois faire pour avoir le bug ?
