### ISSUE TITLE
Team queue join

### ISSUE THREAD

**Issue by Yuuki59** [pokepixelserv/pokepixelpublic#221]
Savoir qui nous affronte 
Exemple : Le joueur ***** vous lance un combat accepté ou non

**Comment by Flashback083** [comment]
Accepté ou non ? Tu vas pas refusé un combat de team de toute façon :/

**Comment by Zkulls** [comment]
je trouve mieux que ce soit des challenger qui ne soit pas connu à l'avance aussi.

**Comment by Yuuki59** [comment]
je trouve que ça serai mieux de savoir à qui on a faire

**Comment by Zkulls** [comment]
tu veux juste pas combattre les joueurs strats x) Genre Vawpire

**Comment by Flashback083** [comment]
Bah savoir qui ok, mais yaura juste un message dans le tchat et vous aurez pas la possibilité de refusé
