### ISSUE TITLE
/deleteclaim

### ISSUE THREAD

**Issue by Yuuki59** [pokepixelserv/pokepixelpublic#222]
Première chose : c'est agaçant de trouvé les maj dans un pseudo , faudrai essayer que la commande marche que avec la première majuscule 

Deuxième chose : sur les règles du serv on a pas ajouté que les modo peuvent /deleteclaim

**Comment by Flashback083** [comment]
J'ai pas compris le premier soucis
Et sur les règles on a le droit de le faire que si un mois tour à boss

**Comment by Yuuki59** [comment]
je vois ta rien compris du tout x)
la première chose : exemple pour /seen tu dois mettre toute les maj du pseudo joueur (PikaBosS) 
et le deuxième je parle qu'il est pas écrit dans les règles que le modo à la perm de /deleteclaim

**Comment by Flashback083** [comment]
Pour le /seen je peux rien faire
Pour les règles modo tu parle de quel règle ? (Où exactement ?)

**Comment by Yuuki59** [comment]
Sur le site

**Comment by Zkulls** [comment]
Où sur le site?
