### ISSUE TITLE
Kit Underground

### ISSUE THREAD

**Issue by SandzaH** [pokepixelserv/pokepixelpublic#227]
Rajouter un kit permettant de récupérer les outils (marteau et pioche) en cas de perte

**Comment by Flashback083** [comment]
il y a déjà /kit lepetitmineurillustré ça ne va pas ?

**Comment by SandzaH** [comment]
Hum faut Que je test mais quand je faisait /kits il n'y avais rien qui s'affichait

**Comment by SandzaH** [comment]
Miss clic ...
