### ISSUE TITLE
Nouveau salon textuelle 

### ISSUE THREAD

**Issue by Yuuki59** [pokepixelserv/pokepixelpublic#234]
On pourrai créer un salon "Citation" 

bon juste une demande car je trouve que ça pourrai être cool x)

**Comment by SkyTizouk** [comment]
Dans quel but ?

**Comment by Yuuki59** [comment]
Je suis sur qu'on a des poétiques sur le serv , le bon salon pour le faire

**Comment by SkyTizouk** [comment]
On avait déjà mis un channels comme ça, mais les seul métaphore qu'il y avait étaient sexuelles :/

**Comment by Yuuki59** [comment]
ah mais on pourrai faire en réglè ce salon pour plus qu'il y a ça

**Comment by Flashback083** [comment]
Bof, pas trop d'accord, je trouve pas ça des plus utiles et bon, rajouter un channel à surveiller, sans façon :/

**Comment by SkyTizouk** [comment]
Donc c'est non ?

**Comment by Flashback083** [comment]
Pour moi non

**Comment by Zkulls** [comment]
je vois pas l’intérêt non plus. Et ils ont déjà pas mal de salon pour user de leurs art déjà uhuh
