### ISSUE TITLE
Nouveau Pnj 

### ISSUE THREAD

**Issue by Yuuki59** [pokepixelserv/pokepixelpublic#235]
On pourrai faire un pnj qui vend des tome ancien ?
pour certaine quêtes c'est dure de trouvé

**Comment by Zkulls** [comment]
Non, c'est justement fait exprès, vue que les tomes sont rare et trouvable seulement dans les coffre donjons ou via achat joueur.

**Comment by SkyTizouk** [comment]
Les donjons sont pas désactivés en ressource ?

**Comment by Zkulls** [comment]
les vanilla non

**Comment by Zkulls** [comment]
donc tu peux avoir des tomes

**Comment by SkyTizouk** [comment]
Donc non, on laisse comme ça
