### ISSUE TITLE
SemiRP coffre de gemmes

### ISSUE THREAD

**Issue by Sain34** [pokepixelserv/pokepixelpublic#24]
Bonjour suite a un giveall d'une pièce en diamant je les transformer et pièce rouillés et échanger contre un coffre de gemmes (aucun srenn) je les ouvert et j'ai obtenu  Un sachet 
![image](https://user-images.githubusercontent.com/42889158/44944884-f89a3200-adde-11e8-98a8-5e6944ef384c.png)

voila si il serait possible davoir un coffre a gemmes et pouvoir réglée ce problem de coffre merci =)

**Comment by Flashback083** [comment]
Fix ! thx
