### ISSUE TITLE
Soucis ville tuto avec pnj d'échange

### ISSUE THREAD

**Issue by Zkulls** [pokepixelserv/pokepixelpublic#241]
- Pnj d'échange avec qui on ne peut pas trade
![05 (2)](https://user-images.githubusercontent.com/44169217/64083993-c50e2280-cd26-11e9-95eb-e51e87c68a64.png)
- Quand on trade avec un pnj d'échange pour un pokemon qui évolue en échange ça fait le bug ou tu freeze pas mais tu ne peux plus rien faire

**Comment by Flashback083** [comment]
Premier bug : 
Normalement fix, il demandait une form spécial du pokémon, ce qui ne devrait pas faire donc à voir si ça se reproduit
Deuxieme bug : Fix temporaire, j'ai enlevé les pokés qui évolue en échange, ça a l'air d'être à cause de pixelmon donc à voir le fix dans les prochaines maj
