### ISSUE TITLE
Permissions zone boss nouveau spawn

### ISSUE THREAD

**Issue by Zkulls** [pokepixelserv/pokepixelpublic#247]
Retirer les différentes possibilité ci-dessous à la zone du boss en (x:43022 y:60 z:10931)

~~- Interdire la création de home~~
~~- Interdire le /tphere ou les personnes qui font un /tpa d'être /tpyes ou /tpaccept pour être tp dans       la zone pour que leurs seul accès soit l'entrée de la zone~~
~~- Interdire le /fly~~
- Interdire le /back pour retourner dedans
~~- Interdire les joueurs de mettre des bateaux~~
Voilà je ne pense pas en avoir oublier. Merci d'avance :)

**Comment by Flashback083** [comment]
Plop tout est bon, y'a que le /back que c'est un peu plus compliqué, faudrait mettre un truc genre quand il exit le claim il est TP 2 fois, mais quand il meurt je sais pas si je peux bloquer le /back :/

**Comment by Zkulls** [comment]
Ah, bon pas grave.
le /back je pensais surtout aux joueurs sans stuff ou ceux qui meurent bêtement pour évité qu'il /back sans arrêt et qu'il full regen le boss à cause de ça x)
Pas grave ça ajoutera de la difficulté ¯\_(ツ)_/¯
Merci :p

**Comment by SkyTizouk** [comment]
On a réussi à le bloqué pour Shannox pourtant

**Comment by Zkulls** [comment]
C'est bien bloqué, merci :p

**Comment by Zkulls** [comment]
le  /back aussi apparemment
