### ISSUE TITLE
Monde event

### ISSUE THREAD

**Issue by Yuuki59** [pokepixelserv/pokepixelpublic#249]
Remettre l'option de ne pas perdre son inventaire , ça serai plus pratique
surtout pour des test quand on doit se suicidé

**Comment by SkyTizouk** [comment]
Ben, quand on meurt on perd toujours notre stuff x)

**Comment by Zkulls** [comment]
et il y a le système qui clear l'inventaire des joueurs au spawn quand il apparaissent sur la plaque de pression

**Comment by Yuuki59** [comment]
Je peux pas l'enlever ?

**Comment by Zkulls** [comment]
si ça a été mis, c'pas pour rien x)
Genre imagine ils font un event avec des épée sharpness 10 recul 10 et par la suite tu fais un event pvp et qu'ils ont toujours l'épée dans leurs inventaire.
Juste rip ton event

**Comment by Yuuki59** [comment]
Bah j'ai fait l'event je l'ai est kill mais ils sont revenus avec leur inventaire ><

**Comment by Flashback083** [comment]
Donc ils perdent pas leur inventaire ?
Pas sûr d'avoir compris, aussi tu l'as fais où l'event ? (les positions)

**Comment by Yuuki59** [comment]
Si ta bien compris ,pour les coordonnées 560 -1717 si je me souviens bien
