### ISSUE TITLE
permissions builder

### ISSUE THREAD

**Issue by SandzaH** [pokepixelserv/pokepixelpublic#255]
quelques soucis sur les permissions des builders (je sais pas les quels exactement juste un ticket a faire pour s'en souvenir)

**Comment by Flashback083** [comment]
Zkulls a essayé de me mettre les perm, mais je n'avais pas accès à world edit (et je pouvais pas casser et poser partout en monde event mais comme y'a une histoire de claim je sais pas), et j'ai pas non plus le /tp ou /warp

**Comment by SandzaH** [comment]
Soucis commande WE 
cdn.discordapp.com/attachments/316192380975972353/628671306744725505/unknown.png 
[21:15] Ryioku: ça me met ça quand je veux utiliser we
[21:15] Ryioku: mais maintenant j'arrive à cliquer avec la hache

**Comment by Flashback083** [comment]
essaye /wea ?

**Comment by SandzaH** [comment]
[18:51] Ryioku: you are lacking the permission node: fawe.admin

**Comment by Flashback083** [comment]
et là ?

**Comment by SandzaH** [comment]
[18:59] Ryioku: tjr la meme
