### ISSUE TITLE
Pwiki

### ISSUE THREAD

**Issue by M-Lockpin** [pokepixelserv/pokepixelpublic#259]
Comme le pokedex donne que très peu d'info comparé au /pwiki je suggère de le remettre

**Comment by M-Lockpin** [comment]
Et surtout faut avoir déjà capturé de poké pour voir les infos donc c'est naze

**Comment by Flashback083** [comment]
Du coup pour le pwiki faudra attendre que le dev update le plugin

**Comment by Flashback083** [comment]
Fix lors de la prochaine update pixelmon
