### ISSUE TITLE
Niveau 27 bug

### ISSUE THREAD

**Issue by Areolame** [pokepixelserv/pokepixelpublic#26]
Bonjour, plusieurs joueurs se sont plains atteindre le niveau 27, minecraft vanilla, et ne pas pouvoir le dépasser. Serrait-il possible de vérifier cela ?
Merci par avance

**Comment by Flashback083** [comment]
Je n'arrive pas du tout à comprendre pourquoi du coup, en attendant, un pnj est disponible au spawn, via le pnj Fl4shb4ck08A sur le centre pokémon
