### ISSUE TITLE
Duplication d'xp

### ISSUE THREAD

**Issue by Clooooud** [pokepixelserv/pokepixelpublic#29]
Yop ! J'ai découvert récemment que lorsque l'on faisait /xpp ça nous donner une pouch d'xp cependant, j'ai aussi remarqué que le /xpp 1 ne prend pas d'xp alors qu'il en donne, il en donne peu (1 point d'xp) mais il suffit de le faire beaucoup pour monter de levels rapidement sans farmer

**Comment by Flashback083** [comment]
Plugin désactivé car je ne trouve plus mon code ;_;
(Je le recoderais si vraiment y'en a besoin)
