### ISSUE TITLE
Grade S-Animateur

### ISSUE THREAD

**Issue by Myuzuka** [pokepixelserv/pokepixelpublic#309]
Changer les perms, le grade n'as aucune perm pour le moment
(Vu qu'on aime pas les Animateur, on laisse le grade à l'abandon :ragecry: | Je t'aime Flash)

**Comment by Myuzuka** [comment]
Et qu'il soit visible sur le Tab + Tchat

**Comment by Myuzuka** [comment]
Manque /kick /tempmute en monde Event et Semirp et le /ban /tempban en monde Event
Sky n'arrive pas a me mettre ces perm apparament

**Comment by SkyTizouk** [comment]
Eu c'est surtout qu'elles y sont et sont censées marchés
