### ISSUE TITLE
/eventmanager

### ISSUE THREAD

**Issue by Myuzuka** [pokepixelserv/pokepixelpublic#318]
Voir, si possible, de pouvoir créer un event mais pour un autre Animateur via la commande "/em create"

**Comment by Myuzuka** [comment]
Exemple de commande donner par toi Flash : /em changeorganisateur <ancien nom de l'animateur> <nom event> <new nom anim>

**Comment by Myuzuka** [comment]
La commande suivante ne fonctionne pas au SemiRP: /em changedate [Organisateur] [Nom event] [NewDate] - Permet de changer la date d'un event

**Comment by Flashback083** [comment]
Changedate fix
