### ISSUE TITLE
[Pixelmon] Bug d'attaque

### ISSUE THREAD

**Issue by Flashback083** [pokepixelserv/pokepixelpublic#4]
L'attaque Hurlement (Roar) passe en Hurle-Temps

**Comment by Tsuyokami** [comment]
bonjour, 
j'ai également constater un problème avec les attaques, quand un pokémon évolue et qu'il apprend par la même occasion une capacité c'elle ci n'est pas prise en compte par le jeu et le pokémon conserve son ancienne capacité. 
Dans l'attente d'une réponse, le plus rapidement possible merci.

**Comment by Flashback083** [comment]
Tu es le seul qui a ça ?
