### ISSUE TITLE
Ajouter une commande de battle avec rules

### ISSUE THREAD

**Issue by Areolame** [pokepixelserv/pokepixelpublic#46]
Permettre une commande qui propose un combat contre un joueur avec les clauses OU, bag clause, OHKO clause...

**Comment by Flashback083** [comment]
C'est à dire ? Enfin, un truc qui ouvre le GUI du battle rule ? 
Aurais tu une idée plus précise de comment la commande fonctionnerait ?

**Comment by Areolame** [comment]
Le pixelmatch cela vérifie que tu respectes les clauses. Est-ce c'est possible de le faire comme une commande normal

**Comment by Flashback083** [comment]
Donc ça lance automatiquement le combat si la clause est respecté ? 
Le GUI apparait dans PM non ?

**Comment by Areolame** [comment]
Oui, avec la possibilité de Show team donc de choisir son lead

**Comment by Flashback083** [comment]
Tu pourrais me donner un exemple d'a quoi ressemblerait la commande ?

**Comment by Areolame** [comment]
./challenge [pseudo]

**Comment by Flashback083** [comment]
ah donc ça envoie une invitation, pas un truc comme /pokebattle

**Comment by Areolame** [comment]
Oui pour les champions

**Comment by Flashback083** [comment]
Ya t-il besoin de prendre en compte la fin de la battle ?

**Comment by Flashback083** [comment]
Et c'est quoi la différence avec le fait de lancer le pokémon contre un dresseur ?

**Comment by Areolame** [comment]
Le temps de mettre toutes les règles à chaque combats
Et non pas besoin de prendre en compte la fin de bataille, juste gagner du temps

**Comment by Flashback083** [comment]
Du coup, quel sont le règles à mettre ? (en plus de la team preview ?)

**Comment by Areolame** [comment]
Bag clause, OU, OHKO clause, Evasion Clause, sleep clause
