### ISSUE TITLE
Bug de Daily reward

### ISSUE THREAD

**Issue by Areolame** [pokepixelserv/pokepixelpublic#55]
Checker le 18 ème jour du daily reward voir si il y a un bug.
Il s'agit d'une pièce rouillé !

**Comment by Flashback083** [comment]
J'ai bien reçu le coffre, et le coffre m'a bien donné la piece :/

**Comment by Flashback083** [comment]
D'autres gens ont eu ce soucis ? :/

**Comment by Flashback083** [comment]
Pas de nouvelle, je close
