### ISSUE TITLE
[Pixelmon] bug de minage

### ISSUE THREAD

**Issue by UnPandaPasBo** [pokepixelserv/pokepixelpublic#7]
quand je mine et il y a un block trop haut,et quand je saute et que je maintient click gauche ca peut le casser lentement.

**Comment by Flashback083** [comment]
C'est un bug serveur ou directement minecraft ?

**Comment by Flashback083** [comment]
Pas de réponse, je clôture, réouvrir le ticket si le bug survient à nouveau !
