### ISSUE TITLE
Todo Tour Combat

### ISSUE THREAD

**Issue by Zkulls** [pokepixelserv/pokepixelpublic#84]
les dresseurs de la tour combat ne donne plus de pièce de combat une fois vaincu.
C'était 1 pièce/par victoire (il me semble)

**Comment by Flashback083** [comment]
Plop, tu peux me dire quels pnj de la tour combat sont censé en donné ? Tous ?

**Comment by Zkulls** [comment]
oui chaque dresseurs, fin en tout cas c'était comme ça avant que je fasse ma pause sur le serveur
