### ISSUE TITLE
AzmaWorld

### ISSUE THREAD

**Issue by Azmagane** [pokepixelserv/pokepixelpublic#85]
Il me faudrait la possibilité de pouvoir faire spawn des entités manuellement, je pensais que seul le spawn naturel était désactivé mais la c'est TOUTE possibilités de spawn les entités.

Il faudrait également me permettre de donner la perm /azma à d'autres joueurs ( je vais avoir besoin de gens pour tester ).

**Comment by Flashback083** [comment]
Niveau entité c'est mob + animal ou que l'un des deux ?
Pour la perm azma, faut voir a qui la donné car soit j'ai une liste soit je donne la perm a telle joueur ?

**Comment by Azmagane** [comment]
Il me faut toute les entités ( pour ça que j'ai dit entité et pas uniquement mob ).
Pour le /azma pour le moment je pense que le donner aux staffs pour les tests serait déjà bien, j'ouvrirais à l'avenir aux joueurs une fois que j'aurais fini le lobby.

**Comment by Flashback083** [comment]
Dis moi si c'est bon

**Comment by Azmagane** [comment]
Pour le spawn des entités c'bon !

**Comment by Flashback083** [comment]
Ok, si ya un autre soucis jte laisse créer un new ticket !
