### ISSUE TITLE
Clear lag ?

### ISSUE THREAD

**Issue by Estreillia** [pokepixelserv/pokepixelpublic#86]
Ajouter un clear lag (items) comme il y avait avant, car je drop des item et je les retrouve 2 semaine plus tard même place, donc sa ajoute des entité qui ne part pas même lors des redems

**Comment by Flashback083** [comment]
J'ai mis un clear lag toutes les 5 minutes, en attente de réponse si c'est bon ou pas !

**Comment by Estreillia** [comment]
perfect ^^

**Comment by Flashback083** [comment]
S'il y a un soucis avec cette méthode, je vous laisse créer un nouveau ticket !
