### ISSUE TITLE
Glas Tempête/Transparent

### ISSUE THREAD

**Issue by Zkulls** [pokepixelserv/pokepixelpublic#89]
Trouver une solution pour les 2 glas de ho-Oh/Lugia vue que le monde ressources n'a plus de structures. Via une quête ou autre..

**Comment by Estreillia** [comment]
Il a toujours des structure en ultra monde, j'ai est fouillé beaucoup et pour le moment j'ai trouvé que 1 glas, mais sa veut dire qu'il en a bien dans les structure en ultra monde, mais après a vous de voir si vous souhaitez faire une quête ^^

**Comment by Zkulls** [comment]
l'ultra monde n'est pas reset il me semble donc a partir d'un moment il y aura pu rien et il est claim admin
