### ISSUE TITLE
[inventaire] Disparition item sur enclume

### ISSUE THREAD

**Issue by Igers0** [pokepixelserv/pokepixelpublic#9]
J'avais déjà eu le cas, mais je pensais que c'était uniquement sur le coup, et ça vient de m'arriver une nouvelle fois ..
Lorsqu'une enclume casse, l'item récupéré disparait totalement avec l'enclume.

**Comment by Flashback083** [comment]
ça arrive à 100% ?

**Comment by Igers0** [comment]
sur 2 fois où l'enclume a cassé, oui. Je vais retenter et te dire ça.
Pour info, la première fois que ça m'est arrivé, c'était avant la maintenance.

**Comment by Igers0** [comment]
Bon 3° essai fait et je confirme, 100%. L'enclume casse, et l'item récupéré (fusionné) disparait.
(ps : pourquoi je ne peux pas changer les label?)
