### ISSUE TITLE
Prix minimum boutique ?

### ISSUE THREAD

**Issue by Estreillia** [pokepixelserv/pokepixelpublic#90]
Certain item sont censer avoir un prix minimum ou devrais en avoir telles que ceux ci =>
éclats verts = 500k
mega gemmes( autre que tenefixe et gengarite) = 150k
shulkeur crystal/diams/obsi = 100k
shulkeur or/fer = 75k
shulkeur normal = 50k
lanterne mers = 10k/u
livre enchant ( mis avec un tome antique, genre efi 6 fortune 4 solidité 4, etc) = 125k

**Comment by Estreillia** [comment]
tous ses prix sont que des exemple il peuvent être modifier( a l'exception des éclats vert)

**Comment by Flashback083** [comment]
éclats verts = 500k
c'est quoi le nom anglais ?

**Comment by ZeFious** [comment]
Jade Shard

**Comment by Elecrton78** [comment]
Pour les mega gemmes autre que tenefixe et gengarite je vois plus 300k voir 450k

**Comment by Zkulls** [comment]
au pire on peut voir via le marchand de gemme contre pièces combat vue que les pièces combat le prix à la caravane le prix est de 125K/u ou le modif lui du coup

**Comment by Flashback083** [comment]
Pour chaque type d'enchant, vous me dite la base que vous pensez que ça vaut en $
Ensuite, pour tout les livres vous me dites combien j'ajoute au prix / level
Exemple : 
Feather Falling IV (C'est forcément puissance 1 minimum si je me trompe pas)
Donc le prix de base :
700 (avec le level 1)
Puis disons 200 par level
700 + (3 * 200) = 1300
Tout le monde a suivi ? xD
Maintenant ma question est :
Combien de $ en plus par level > 1 ?
Combien de $ mini pour chaque type d'enchant ?

**Comment by Flashback083** [comment]
ne pas pouvoir vendre de hache au shop
