### ISSUE TITLE
ajout pnj end

### ISSUE THREAD

**Issue by Estreillia** [pokepixelserv/pokepixelpublic#91]
Je poste ici pour que la demande de zkulls soit plus visibles, il demandait si il etait possile ajouter les block mauvede l'end au pnj end du warp shop (block de purpur)

**Comment by Zkulls** [comment]
Non je parlais des blocs de temples d'aquamarine qu'on trouve dans les biomes océan à la base vue qu'il n'y a plus les structures dans le monde ressources. Mais oui après pourquoi pas ajouter les autres blocs des forteresse de l'end à son marchand ^^

**Comment by SkyTizouk** [comment]
Vous êtes toujours ok ?
Autrement je rajoute ça demain, par contre ça implique la suppressions de la quette qui, n'aura donc plus aucun intérêt.
