### ISSUE TITLE
Visibilité du staff en UG

### ISSUE THREAD

**Issue by Zkulls** [pokepixelserv/pokepixelpublic#92]
Ajouter le grade du staff en UG car quand ils y sont et qu ils écrivent dans le tchat leurs pseudo est bleu du coup les joueurs voient pas qu'ils font parti du staff
"Demande d'estreillia"

**Comment by SkyTizouk** [comment]
Etant donné que les staffs n'ont pas les permissions en Ug, pourquoi ?

**Comment by Estreillia** [comment]
Pourquoi? Comme l’a expliqué zkulls pour un meilleur visibilités, car des fois je suis ug je repond question, mais le joueur redemande comme meme puisquil na pas eu de reponse de quelqun du staff en quelque sorte
