### ISSUE TITLE
Agro pokemon ?

### ISSUE THREAD

**Issue by Estreillia** [pokepixelserv/pokepixelpublic#95]
Yuuki suggère de retiré l'aggro des pokemon, qui je l'avoue être très désagréable lorsque tu veut build par exemple, de plus j'avais essayer d'utiliser des repousse, mais sa ne fesait rien, je me fesait toujours agro, alors ce serait nice de retiré l'agro, car c'est relou a certain moment, d'être obliger de prendre 1 poke puis de le faire crever dans la lave pour que tu est aucun poke vivant, donc que ne te fasse plus agro(désoler petit GrotteDeNez tu est mort tant de fois ;'| )

**Comment by Flashback083** [comment]
Changé pour le prochain redem
