### ISSUE TITLE
Apparition pokemon en francais ?

### ISSUE THREAD

**Issue by Estreillia** [pokepixelserv/pokepixelpublic#97]
Possibilité que quand un shiny apparait il soit écrit en francais, ou entre parenthese
ou comme zefious la dit un truc comme nymphali/sylveon

**Comment by Flashback083** [comment]
C'est à dire ? Quand un pokémon spawn normal il est en français le  nom ?
Enfin, si vous voulez voir le nom en français, il faut mettre MC en français juste non ?

**Comment by Estreillia** [comment]
nop genre sa va écrire https://image.prntscr.com/image/AINIyUMmSH238vpVPCx_zw.png
Mais ce qui serais bien serait ''Un sentret/fouinette est spawn dans le biome plains'', comme sa ceux qui connaissent juste les nom francais vont savoir quel genre de poke chercher

**Comment by Flashback083** [comment]
je peux pas voir l'image 
Et c'est pas possible je pense, car c'est coté client et c'est dans le code de pixelmon directement 
La traduction des pokémons est seulement coté client, pas serveur malheureusement

**Comment by Estreillia** [comment]
daccord ^^
