### ISSUE TITLE
Auto Clear Item

### ISSUE THREAD

**Issue by ZeFious** [pokepixelserv/pokepixelpublic#98]
Il y a pas mal de gens qui se font clear des trucs qu'ils jettent au sol pour donner à quelqu'un d'autre, ou pas erreur, bref ils se font clear leur items et ça les fait rager, je voulais savoir si y'aura pas moyen de mettre un/deux petites messages (Pour pas trop spam) pour prévenir qu'il va y avoir un clear d'item dans X secondes, j'pensais a 30 et 10 secondes puis clear ou un truc du genre

**Comment by Flashback083** [comment]
Ajout d'un message quand il reste 
1 minute
30 secondes
10 secondes
