### ISSUE TITLE
Problème coffre item leg  etc,..

### ISSUE THREAD

**Issue by Zkulls** [pokepixelserv/pokepixelpublic#99]
Ce soir après les crash j'ai pris un coffre item evo au marchand à la caravane mais quand j'ai voulu use le coffre ça l'a posé simplement au sol du coup je n'ai rien reçu (j'ai aussi testé clique droit en l'air), d'autre joueurs on eu le même soucis avec ceux des /kit.

**Comment by Flashback083** [comment]
Yep je suis au courant, je vais faire une maintenance cette nuit pour essayer de fix ça
